name: Build talks.js and outreach.js from TSV

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate JS files from TSV
        run: |
          npm install
          node scripts/generate_js_from_tsv.js

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add js/talks.js js/outreach.js
          git diff --cached --quiet || git commit -m "Auto-update talks.js and outreach.js from TSV"
          git push