name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Run your custom generation scripts
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate JS from TSV
        run: |
          npm install
          node scripts/generate_js_from_tsv.js
      
      - name: Download arXiv metadata JS
        run: |
          mkdir -p js
          curl -sSL https://arxiv.org/a/paya_c_1.js -o js/publications.js

      - name: Commit and push generated JS files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add js/*.js
          git diff --cached --quiet || git commit -m "Update generated JS files [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Clone CV repo
        run: |
          git clone https://github.com/CarlosP24/cv.git cv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3

      - name: Install latexmk
        run: tlmgr install latexmk

      - name: Build CV PDF
        shell: bash
        run: |
          cd cv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          ./update_cv.sh \
            "https://api.zotero.org/users/13410489/publications/items?format=bibtex" \
            "../js/talks.js" \
            "../js/outreach.js" \
            "../js/funding.js" \
            "../js/awards.js" \
            "Payá, Carlos" \
            "MyCV.pdf"
          cp MyCV.pdf ../files/CV.pdf

      - name: Commit and push CV.pdf
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add files/CV.pdf
          git commit -m "Update CV.pdf from CV repo"
          git push

      # 2. Build your site (if using Jekyll or another static site generator)
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      # 3. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4